# GitHub Sponsors
github: [your-github-username]

# Ko-fi
# kofi: your-ko-fi-username

# Patreon
# patreon: your-patreon-username

# Open Collective
# open_collective: your-open-collective-username

# Tidelift
# tidelift: pypi/runpod-llm-manager

# Community Bridge
# community_bridge: your-project-name

# Buy Me a Coffee
# buy_me_a_coffee: your-username

# Custom
# custom: ['https://www.paypal.me/your-paypal-link', 'https://donate.example.com']
