repos:
  # Black - Python code formatter (essential for consistent formatting)
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3

  # Basic pre-commit hooks for file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-toml

  # Note: Additional linting hooks (flake8, bandit, safety) removed due to configuration issues
  # Run manually as needed:
  # - python security_utils.py scan (vulnerability scanning)
  # - python security_utils.py report (comprehensive security report)
  # - flake8 . (code linting)
  # - bandit -r . (security linting)
